version: 2.1

executors:
  node:
    docker:
    - image: circleci/node:10

jobs:
  node-server: 
    executor: node
    steps:
      - checkout
      - run: 
          command: npm install
          working_directory: ./server
      - run:
          command: npm test
          working_directory: ./server

  react-client:
    executor: node
    steps:
      - checkout
      - run: 
          command: npm install
          working_directory: ./client
      - run: 
          command: npm test
          working_directory: ./client

workflows:
  version: 2
  build_deploy:
    jobs:
      - node-server:
          filters:
            branches:
              only: master
      - react-client:
          filters:
            branches:
              only: master
